### Register User API
POST http://localhost:8000/api/users/
Content-Type: application/json

{
    "username": "sod",
    "password": "12345",
    "name": "Test"
}

### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "username": "jon",
    "password": "12345"
}

### Get Current User API
GET http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: bd0afdac-d62d-4d9a-a9a2-a29067c50f10

### Update Current User API
PATCH http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: bd0afdac-d62d-4d9a-a9a2-a29067c50f10

{
    "name": "Jon Targaryen"
}

### Logout User API
DELETE http://localhost:8000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 690179a0-624b-43d7-8081-1a18556f8494

### Create Contact API
POST http://localhost:8000/api/contacts HTTP/1.1
Content-Type: : application/json
Authorization: e96f0ff4-31b6-495e-a4be-55734f73fd02
Accept: application/json

{
    "first_name": "Eddard",
    "last_name": "Stark",
    "email": "bran@winterfell.com",
    "phone": "1234567"
}

### GET Contact API #622
GET http://localhost:8000/api/contacts/622 HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

### Create Contact API #622
PUT http://localhost:8000/api/contacts/622 HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

{
    "first_name": "Arya",
    "last_name": "Stark",
    "email": "bran@winterfell.com",
    "phone": "1234567"
}

### Delete Contact API #622
DELETE http://localhost:8000/api/contacts/622 HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

### Search Contact API
GET http://localhost:8000/api/contacts?email=bran HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

### Create Adress API
POST http://localhost:8000/api/contacts/623/addresses HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

{
    "street": "Kingsroad",
    "city": "Winterfell",
    "province": "North Island",
    "country": "Westeros",
    "postal_code": "12345"
}

### Get Adress API #41
GET http://localhost:8000/api/contacts/623/addresses/41 HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

### Update Adress API #41
PUT http://localhost:8000/api/contacts/623/addresses/41 HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

{
    "street": "Nightwatch",
    "city": "Winterfell",
    "province": "North Island",
    "country": "Westeros",
    "postal_code": "12345"
}

### Remove Adress API #41
DELETE http://localhost:8000/api/contacts/623/addresses/41 HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json

### List Adress API #41
GET http://localhost:8000/api/contacts/623/addresses HTTP/1.1
Content-Type: : application/json
Authorization: 645586c9-252a-46b7-b187-752229bbe34a
Accept: application/json